#preload= ~/.config/backgrounds/my_keymap.png
#wallpaper = , contain:~/.config/backgrounds/my_keymap.png

preload= ~/.config/backgrounds/my_keymap.png
preload= ~/.config/backgrounds/shaded_landscape.jpg

wallpaper = eDP-1, contain:~/.config/backgrounds/my_keymap.png
wallpaper = HDMI-A-1, contain:~/.config/backgrounds/shaded_landscape.jpg
#preload = ~/.config/backgrounds/shaded.png
#wallpaper = , ~/.config/backgrounds/shaded.png
